name: lighthouse_admin
description: A backend management system

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.10
  # https://github.com/flutter/plugins/tree/master/packages/package_info
  package_info: ^2.0.0
  #get路由 状态管理 依赖注入 https://github.com/jonataslaw/getx
  get: ^3.26.0
  #key-value存储 https://github.com/jonataslaw/get_storage
  get_storage: ^1.4.0
  #toast库 https://github.com/MMMzq/bot_toast
  bot_toast: ^3.0.5
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^6.0.2
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.3.1+1
  # 加密库 https://github.com/leocavalcante/encrypt
  encrypt: ^5.0.0-beta.1
  # data endecode https://github.com/dart-lang/convert
  convert: ^3.0.0
  # 小数计算 https://github.com/a14n/dart-decimal
  decimal: ^1.0.0
  # loading动画 https://github.com/jogboms/flutter_spinkit
  flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

flutter_intl:
  enabled: true
